### ISSUE TITLE
Chapter3：WAICの値が書籍と一致しない件について

### ISSUE THREAD

**Issue by pagumi-bayesian** [uenotakato/Machine-Learning-in-Web-Optimization-with-CmdStanPy#1]
初めまして。こちらのリポジトリを拝見し、cmdstanpyとarvizを使ったMCMCについて勉強させていただいております。

1点、Chapter3のnotebookの最後に記載されている「**モデルの推定結果は書籍と同じだが，WAICの値が異なる**」について、原因を調べてみました。

[こちらのページ](https://www.jax.org/news-and-insights/jax-blog/2015/october/lp-in-stan-output)によると、stanの`lp__`で返される値は、観測値の対数尤度から定数項(=パラメータに依存しない項)を除いたもののようです。

定数項も含んだ完全な状態の対数尤度を計算するには、[arvizのCreating InferenceDataページ](https://python.arviz.org/en/stable/getting_started/CreatingInferenceData.html#from-cmdstanpy)を見る限り、generated quantitiesブロックを使う必要があるようです。

例えば`model_comb.stan`ですと、stanファイルの最後に以下のような記述を加えます。

```stan
generated quantities {
    vector[N] log_lik;
    
    for (i in 1:N) {
        log_lik[i] = binomial_lpmf(clicks[i] | n[i], theta[i]);
    }
}
```
その後、MCMCを実行し結果を`az.from_cmdstanpy`で取り出す際に、以下のようにlog_likelihoodを定義すればよいようです。
```python
cmdstanpy_data_comb = az.from_cmdstanpy(
    posterior=fit_comb,
    log_likelihood="log_lik",
)
```
この手順でWAIC(`p_waic`)を計算したところ、私の環境では**comb2が3.66、intが2.08**となり、書籍の結果と近い値となりました。

**Comment by uenotakato** [comment]
issueを立てていただきどうもありがとうございます。まさに一番気にしていた点であり，ご指摘いただき大変感謝しております。

実装を試し次第，こちらのリポジトリへも変更を反映させようと思います。

**Comment by uenotakato** [comment]
実装を試し，WAIC（p_waic）について学習してお示しいただいたところについて変更しました。
p_waicの結果もcombが3.78， intが2.07となり書籍の結果と近いものとなりました。ご教授いただき，どうもありがとうございました。

**Comment by pagumi-bayesian** [comment]
よかったです！！
ご丁寧にご連絡いただきありがとうございます！！
